# Generated by Django 5.2.10 on 2026-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('enrollment_date', models.DateField()),
                ('enrollment_month', models.IntegerField()),
                ('enrollment_day_of_week', models.IntegerField()),
                ('time_spent_hours', models.FloatField()),
                ('interaction_count', models.IntegerField()),
                ('video_completion_rate', models.FloatField()),
                ('assessment_score', models.FloatField()),
                ('feedback_score', models.FloatField()),
                ('avg_completion_rate', models.FloatField()),
                ('avg_assessment_score', models.FloatField()),
                ('engagement_score', models.FloatField()),
                ('completion_status', models.IntegerField()),
                ('anomaly_flag', models.IntegerField()),
                ('is_high_feedback', models.IntegerField()),
                ('course_quality_label', models.IntegerField()),
            ],
        ),
    ]
